import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 12,
  },
  header: {
    flex: 0.15,
    minHeight: 30,
  },
  body: {
    flex: 1,
  },
  search: {
    borderColor: 'grey',
    borderRadius: 8,
    paddingHorizontal: 20,
    backgroundColor: 'white',
    flex: 0.95,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: 'black',
    marginVertical: 8,
  },
  listItem: {
    padding: 12,
    marginHorizontal: 8,
    marginVertical: 12,
    borderRadius: 8,
    backgroundColor: 'white',
  },
  image: {
    width: '100%',
    height: 220,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  detailsImage: {
    width: '100%',
    aspectRatio: 1.5,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  searchResultView: {
    backgroundColor: 'white',
    zIndex: 1,
    padding: 8,
    borderBottomColor: 'grey',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: 'grey',
    borderLeftColor: 'grey',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  Listprice: {
    fontSize: 18,
    marginVertical: 6,
    fontWeight: 700,
  },
  detailsHeader: {fontWeight: '600', fontSize: 16, marginBottom: 12},
  priceView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: 24,
    marginVertical: 6,
    fontWeight: 700,
  },
  line: {
    height: 0.5,
    width: '100%',
    backgroundColor: '#D3D3D3',
    marginVertical: 8,
  },
  views: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    borderRadius: 10,
    paddingHorizontal: 4,
    position: 'absolute',
    top: 35,
    right: 20,
    alignItems: 'center',
  },
  back: {
    position: 'absolute',
    top: 40,
    left: 15,
    backgroundColor: 'white',
    zIndex: 1,
    padding: 10,
    borderRadius: 30,
  },
  navigate: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  utils: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
    paddingHorizontal: 8,
    borderWidth: 0.3,
    borderRadius: 15,
  },
  utilValues: {fontSize: 16, paddingLeft: 8, color: 'black'},
  searchView: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 8,
    alignItems: 'center',
  },
  count: {fontSize: 12, color: 'black'},
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  button: {
    position: 'absolute',
    bottom: 20,
    backgroundColor: 'black',
    width: '90%',
    marginHorizontal: 20,
    alignSelf: 'center',
    borderRadius: 12,
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    paddingVertical: 20,
    fontSize: 14,
  },
});
